---

hydra:
  callbacks:
    version:
      _target_: freakiir.hydra.callbacks.Version

  job:
    chdir: true

model:
  _target_: freakiir.model.AllPass
  config:
    _target_: freakiir.model.ModelConfig
    sections: 4

pdf:
  epsilon: 1.0e-6

pdf_z: ${pdf}
pdf_p: ${pdf}

defaults:
  - pdf:
      - uniform
  - _self_
