---

hydra:
  callbacks:
    version:
      _target_: freakiir.hydra.callbacks.Version

  job:
    chdir: true

checkpoint:
  dir: checkpoints
  resume: null

model:
  _target_: freakiir.model.AllPass
  config:
    _target_: freakiir.model.ModelConfig
    inputs: 512
    sections: 4
    hidden_features: 2048
    hidden_layers: 4
    negative_slope: 0.2
    down_order: false

pdf:
  _target_: freakiir.__main__._pdf
  epsilon: 1.0e-6

pdf_z: ${pdf}
pdf_p: ${pdf}

trainer:
  _target_: pytorch_lightning.Trainer
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  gradient_clip_algorithm: norm
  gradient_clip_val: 0.5
  max_epochs: -1

defaults:
  - datamodule: random-filter-with-listen-hrtf
  - dataset
  - pdf:
      - uniform
  - _self_
