---

hydra:
  callbacks:
    version:
      _target_: freakiir.hydra.callbacks.Version

  job:
    chdir: true

pdf:
  epsilon: 1.0e-6

pdf_z: ${pdf}
pdf_p: ${pdf}

defaults:
  - pdf:
      - uniform
  - _self_
